services:
  db:
    image: postgres:14
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myapp_development

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && sleep 5 && bundle exec rails server -b 0.0.0.0 -p 3000"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: development

volumes:
  pgdata:
